# Generated by Django 5.0.7 on 2025-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Web Design', 'Web Design'), ('App Development', 'App Development')], max_length=100),
        ),
    ]
