# Generated by Django 5.0.7 on 2025-04-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio1', '0002_alter_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
